# Generated by Django 5.2.7 on 2025-11-05 05:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_courseenrolment_active_status_exam_active_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='courseenrolment',
            old_name='status',
            new_name='level',
        ),
    ]
